### ISSUE TITLE
Not working on Macbook Pro 2021

### ISSUE THREAD

**Issue by YusufGandhi** [vitorgalvao/right-click-workflow#1]
The plugin is not working on my Mac running MacOS Ventura 13.4.1 (22F82). The following is the spec of my Macbook:
<img width="242" alt="image" src="https://github.com/vitorgalvao/right-click-workflow/assets/2329909/f3d64ffe-df44-4671-83fd-ee2c74d0314d">

Any idea?

**Comment by vitorgalvao** [comment]
Please create a [bug report with the template](https://github.com/vitorgalvao/right-click-workflow/issues/new?assignees=&labels=&projects=&template=bug_report.yml). It’s impossible to help you otherwise because there’s not enough information.
